### ISSUE TITLE
Windows-only dependencies?

### ISSUE THREAD

**Issue by jeremydouglass** [Aviv871/Lang871#5]
Is there a particular reason that this project is described as Windows only, even though it is Java? What are the dependencies? The Alpha release jar appears to run fine on MacOS when downloaded and launched.

Also -- would it be possible to create a new release? Or include some very brief instructions for how to build in IDEA?

**Comment by Aviv871** [comment]
Hi,
I updated the README file, it now includes section on how to build using IDEA + I added a new release with the most recent code.

There are no special dependencies expect swing\awt (for the GUI), so I suppose it will work fine on other operations systems (no tested thought).

**Comment by jeremydouglass** [comment]
Thank you so much, @Aviv871. FYI, your project came up in a recent discussion of creating a Hebrew programming language for children, here: 

https://discourse.processing.org/t/writing-a-small-programming-language/24095
